use std::fs;
use std::process::Command;

fn cli_bin() -> &'static str {
    env!("CARGO_BIN_EXE_dsc")
}

fn write(path: &std::path::Path, source: &str) {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("mkdir");
    }
    fs::write(path, source).expect("write fixture");
}

fn bundle(args: &[&str]) -> std::process::Output {
    Command::new(cli_bin())
        .args(args)
        .output()
        .expect("run dsc bundle")
}

#[test]
fn bundles_local_imports_into_single_file() {
    let temp = tempfile::tempdir().expect("tempdir");
    let root = temp.path().join("src");
    write(&root.join("dep.ds"), "export const value = 41\n");
    write(
        &root.join("main.ds"),
        "import { value } from './dep.ds'\nexport const answer = value + 1\n",
    );
    let out = temp.path().join("bundle.js");

    let output = bundle(&[
        "bundle",
        root.join("main.ds").to_str().unwrap(),
        "--out",
        out.to_str().unwrap(),
    ]);
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );

    let emitted = fs::read_to_string(&out).expect("bundle output");
    assert!(
        emitted.starts_with("// Generated by dsc transpile."),
        "{emitted}"
    );
    assert!(emitted.contains("answer"), "{emitted}");
    assert!(
        !emitted.contains("import "),
        "bundle still has an import statement: {emitted}"
    );
    assert!(
        !emitted.contains("./dep.ds"),
        "bundle still references the local module path: {emitted}"
    );
    let balance = emitted.chars().fold(0i64, |depth, ch| match ch {
        '{' | '(' | '[' => depth + 1,
        '}' | ')' | ']' => depth - 1,
        _ => depth,
    });
    assert_eq!(balance, 0, "unbalanced delimiters: {emitted}");
}

#[test]
fn treeshake_produces_minified_output() {
    let temp = tempfile::tempdir().expect("tempdir");
    let root = temp.path().join("src");
    write(&root.join("dep.ds"), "export const value = 41\n");
    write(
        &root.join("main.ds"),
        "import { value } from './dep.ds'\nexport const answer = value + 1\n",
    );
    let plain = temp.path().join("plain.js");
    let minified = temp.path().join("minified.js");

    let a = bundle(&[
        "bundle",
        root.join("main.ds").to_str().unwrap(),
        "--out",
        plain.to_str().unwrap(),
    ]);
    assert!(a.status.success(), "{}", String::from_utf8_lossy(&a.stderr));
    let b = bundle(&[
        "bundle",
        "--treeshake",
        root.join("main.ds").to_str().unwrap(),
        "--out",
        minified.to_str().unwrap(),
    ]);
    assert!(b.status.success(), "{}", String::from_utf8_lossy(&b.stderr));

    let plain = fs::read_to_string(&plain).expect("plain bundle");
    let minified = fs::read_to_string(&minified).expect("minified bundle");
    assert!(
        minified.len() < plain.len(),
        "treeshake output ({len} bytes) must be shorter than plain ({plain_len} bytes)",
        len = minified.len(),
        plain_len = plain.len()
    );
}

#[test]
fn missing_out_is_a_usage_error() {
    let temp = tempfile::tempdir().expect("tempdir");
    let source = temp.path().join("answer.ds");
    write(&source, "export const answer = 42\n");

    let output = bundle(&["bundle", source.to_str().unwrap()]);
    assert_eq!(output.status.code(), Some(1));
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("requires --out"), "unexpected: {stderr}");
}

#[test]
fn help_exits_zero_and_prints_usage() {
    let output = bundle(&["bundle", "--help"]);
    assert!(output.status.success());
    let text = format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    for expected in ["--out", "--treeshake", "--client", "Examples:"] {
        assert!(text.contains(expected), "missing {expected}: {text}");
    }
}
