use std::fs;
use std::process::Command;

fn cli_bin() -> &'static str {
    env!("CARGO_BIN_EXE_dsc")
}

fn write(path: &std::path::Path, source: &str) {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("mkdir");
    }
    fs::write(path, source).expect("write fixture");
}

#[test]
fn file_writes_adjacent_js() {
    let temp = tempfile::tempdir().expect("tempdir");
    let source = temp.path().join("answer.ds");
    write(&source, "export const answer = 42\n");

    let output = Command::new(cli_bin())
        .arg("transpile")
        .arg(&source)
        .output()
        .expect("run transpile");
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );

    let emitted = fs::read_to_string(source.with_extension("js")).expect("emitted JavaScript");
    assert!(
        emitted.starts_with("// Generated by dsc transpile."),
        "{emitted}"
    );
    assert!(emitted.contains("answer"), "{emitted}");
}

#[test]
fn transpile_output_ignores_ambient_environment() {
    // dsc#124: an artifact is determined by source plus deka.json, never by
    // ambient process configuration. Keep the two child environments
    // deliberately incompatible so a newly introduced environment override
    // cannot silently evade this regression test.
    let temp = tempfile::tempdir().expect("tempdir");
    let project = temp.path().join("project");
    let source = project.join("app/main.ds");
    write(&project.join("deka.json"), "{\"name\": \"env-proof\"}\n");
    write(&source, "export const answer = 42\n");

    let first = project.join("first.js");
    let first_run = Command::new(cli_bin())
        .current_dir(&project)
        .env_clear()
        .env("DEKA_MODULE_ROOT", "/not-the-project")
        .env("DEKA_MINIFY", "true")
        .env("DEKA_SOURCEMAP", "true")
        .env("DEKA_EXTERNAL_NODE_MODULES", "react,lodash")
        .env("DEKA_BUNDLER_CACHE", "false")
        .env("HOME", "/first-home")
        .env("USERPROFILE", "C:\\first-home")
        .env("NO_COLOR", "1")
        .env("DEKA_NO_COLOR", "1")
        .env("TERM", "dumb")
        .env("LOG_LEVEL", "debug")
        .args(["transpile", "app/main.ds", "--out"])
        .arg(&first)
        .output()
        .expect("transpile in first environment");
    assert!(
        first_run.status.success(),
        "{}",
        String::from_utf8_lossy(&first_run.stderr)
    );

    let second = project.join("second.js");
    let second_run = Command::new(cli_bin())
        .current_dir(&project)
        .env_clear()
        .env("DEKA_MODULE_ROOT", "/a-different-project")
        .env("DEKA_MINIFY", "false")
        .env("DEKA_SOURCEMAP", "false")
        .env("DEKA_EXTERNAL_NODE_MODULES", "")
        .env("DEKA_BUNDLER_CACHE", "true")
        .env("HOME", "/second-home")
        .env("USERPROFILE", "C:\\second-home")
        .env("NO_COLOR", "")
        .env("DEKA_NO_COLOR", "")
        .env("TERM", "xterm-256color")
        .env("LOG_LEVEL", "error")
        .args(["transpile", "app/main.ds", "--out"])
        .arg(&second)
        .output()
        .expect("transpile in second environment");
    assert!(
        second_run.status.success(),
        "{}",
        String::from_utf8_lossy(&second_run.stderr)
    );

    assert_eq!(
        fs::read(&first).expect("first output"),
        fs::read(&second).expect("second output"),
        "identical source and deka.json must produce identical artifacts"
    );
}

#[test]
fn bytes_length_transpiles_verbatim() {
    // dsc#92: `bytes` is a Uint8Array at runtime, so `bytes.length` is a
    // plain property read -- emission must be the transparent field access
    // with no wrapper or runtime helper.
    let temp = tempfile::tempdir().expect("tempdir");
    let source = temp.path().join("bytes_length.ds");
    write(
        &source,
        "export fn size(b: bytes) number {\n  return b.length\n}\n",
    );

    let output = Command::new(cli_bin())
        .arg("transpile")
        .arg(&source)
        .output()
        .expect("run transpile");
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );

    let emitted = fs::read_to_string(source.with_extension("js")).expect("emitted JavaScript");
    assert!(
        emitted.contains("b.length"),
        "bytes.length must emit as a plain property read: {emitted}"
    );
    assert!(
        !emitted.contains("__deka"),
        "bytes.length must not route through a runtime helper: {emitted}"
    );
}

#[test]
fn preserve_mirrors_tree_and_rewrites_relative_ds_imports() {
    let temp = tempfile::tempdir().expect("tempdir");
    let root = temp.path().join("src");
    write(&root.join("nested/math.ds"), "export const value = 41\n");
    write(
        &root.join("main.ds"),
        "import { value } from './nested/math.ds'\nexport const answer = value + 1\n",
    );
    let out = temp.path().join("generated");

    let output = Command::new(cli_bin())
        .args(["transpile", root.to_str().unwrap(), "--out"])
        .arg(&out)
        .output()
        .expect("run transpile");
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(out.join("nested/math.js").is_file());
    let main = fs::read_to_string(out.join("main.js")).expect("main");
    assert!(
        main.contains("./nested/math.js"),
        "relative import not rewritten: {main}"
    );
}

#[test]
fn bundle_directory_requires_out_and_inlines_imports() {
    let temp = tempfile::tempdir().expect("tempdir");
    let root = temp.path().join("src");
    write(&root.join("dep.ds"), "export const value = 41\n");
    write(
        &root.join("main.ds"),
        "import { value } from './dep.ds'\nexport const answer = value + 1\n",
    );
    let out = temp.path().join("bundle.js");

    let missing = Command::new(cli_bin())
        .args(["transpile", "--bundle"])
        .arg(&root)
        .output()
        .expect("run transpile");
    assert!(!missing.status.success());
    let stderr = String::from_utf8_lossy(&missing.stderr);
    assert!(stderr.contains("requires --out"), "unexpected: {stderr}");

    let output = Command::new(cli_bin())
        .args(["transpile", "--bundle", "--out"])
        .arg(&out)
        .arg(&root)
        .output()
        .expect("run transpile");
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    let emitted = fs::read_to_string(&out).expect("bundle");
    assert!(
        emitted.starts_with("// Generated by dsc transpile."),
        "{emitted}"
    );
    assert!(emitted.contains("answer"), "{emitted}");
    assert!(
        !emitted.contains("./dep.ds"),
        "bundle still has a relative .ds import: {emitted}"
    );
}

#[test]
fn help_describes_preserve() {
    let output = Command::new(cli_bin())
        .args(["transpile", "--help"])
        .output()
        .expect("run transpile help");
    assert!(output.status.success());
    let text = format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    for expected in [
        "--preserve",
        "--bundle",
        "--treeshake",
        "--client",
        "--dev",
        "Examples:",
    ] {
        assert!(text.contains(expected), "missing {expected}: {text}");
    }
}

#[test]
fn transpile_dev_emits_jsxdev_production_emits_jsx() {
    // deka#937 greps `dsc transpile --help` for `--dev` and then compiles
    // `.dsx` with that flag so Fast Refresh gets jsxDEV + DS locations.
    let temp = tempfile::tempdir().expect("tempdir");
    let source = temp.path().join("card.dsx");
    write(
        &source,
        "export fn Card() ReactNode {\n  return <p>hello</p>;\n}\n",
    );
    let prod = temp.path().join("prod.js");
    let dev = temp.path().join("dev.js");

    let prod_run = Command::new(cli_bin())
        .args(["transpile", source.to_str().unwrap(), "--out"])
        .arg(&prod)
        .output()
        .expect("transpile production");
    assert!(
        prod_run.status.success(),
        "{}",
        String::from_utf8_lossy(&prod_run.stderr)
    );

    let dev_run = Command::new(cli_bin())
        .args(["transpile", "--dev", source.to_str().unwrap(), "--out"])
        .arg(&dev)
        .output()
        .expect("transpile --dev");
    assert!(
        dev_run.status.success(),
        "{}",
        String::from_utf8_lossy(&dev_run.stderr)
    );

    let prod_js = fs::read_to_string(&prod).expect("production emit");
    let dev_js = fs::read_to_string(&dev).expect("dev emit");
    assert!(
        prod_js.contains("jsx(") || prod_js.contains("jsxs("),
        "production must call jsx/jsxs: {prod_js}"
    );
    assert!(
        !prod_js.contains("jsxDEV"),
        "production must not emit jsxDEV: {prod_js}"
    );
    assert!(
        prod_js.contains("jsx-runtime"),
        "production must import the production runtime: {prod_js}"
    );
    assert!(
        dev_js.contains("jsxDEV"),
        "transpile --dev must emit jsxDEV: {dev_js}"
    );
    assert!(
        dev_js.contains("jsx-dev-runtime"),
        "transpile --dev must import the development runtime: {dev_js}"
    );
    assert!(
        dev_js.contains("fileName")
            && dev_js.contains("lineNumber")
            && dev_js.contains("columnNumber"),
        "transpile --dev must carry DS source locations: {dev_js}"
    );
}

#[test]
fn refuses_to_overwrite_hand_written_js() {
    let temp = tempfile::tempdir().expect("tempdir");
    let source = temp.path().join("answer.ds");
    write(&source, "export const answer = 42\n");
    write(&source.with_extension("js"), "export const mine = 1\n");
    let output = Command::new(cli_bin())
        .arg("transpile")
        .arg(&source)
        .output()
        .expect("run transpile");
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("was not generated by dsc transpile"),
        "unexpected output: {stderr}"
    );
}

#[test]
fn self_contained_inlines_prelude_for_separate_scopes() {
    let temp = tempfile::tempdir().expect("tempdir");
    let root = temp.path().join("src");
    write(
        &root.join("point.ds"),
        "struct Point {\n  x: number;\n}\nexport const origin = Point { x: 0 }\n",
    );
    write(
        &root.join("main.ds"),
        "import { origin } from './point.ds'\nexport const x = origin.x\n",
    );
    let detached = temp.path().join("detached");
    let contained = temp.path().join("contained");

    let a = Command::new(cli_bin())
        .args(["transpile", root.to_str().unwrap(), "--out"])
        .arg(&detached)
        .output()
        .expect("transpile");
    assert!(a.status.success(), "{}", String::from_utf8_lossy(&a.stderr));

    let b = Command::new(cli_bin())
        .args([
            "transpile",
            "--self-contained",
            root.to_str().unwrap(),
            "--out",
        ])
        .arg(&contained)
        .output()
        .expect("transpile self-contained");
    assert!(b.status.success(), "{}", String::from_utf8_lossy(&b.stderr));

    let detached_point = fs::read_to_string(detached.join("point.js")).expect("detached point");
    let contained_point = fs::read_to_string(contained.join("point.js")).expect("contained point");
    let contained_main = fs::read_to_string(contained.join("main.js")).expect("contained main");
    assert!(
        contained_point.contains("__deka_struct") || contained_point.contains("function Point"),
        "self-contained point.js should inline the struct factory: {contained_point}"
    );
    assert!(
        contained_main.contains("./point.ds"),
        "self-contained isolate emit must keep .ds specifiers, got: {contained_main}"
    );
    assert!(
        !contained_main.contains("./point.js"),
        "self-contained isolate emit must not rewrite .ds imports to .js, got: {contained_main}"
    );
    assert!(
        contained_point.len() >= detached_point.len(),
        "self-contained emit should not be smaller than detached"
    );
}

#[test]
fn self_contained_file_out_dir_writes_the_whole_graph() {
    let temp = tempfile::tempdir().expect("tempdir");
    let root = temp.path().join("src");
    write(
        &root.join("point.ds"),
        "struct Point {\n  x: number;\n}\nexport const origin = Point { x: 0 }\n",
    );
    write(
        &root.join("main.ds"),
        "import { origin } from './point.ds'\nexport const x = origin.x\n",
    );
    std::fs::write(root.join("deka.json"), "{}\n").expect("deka.json");
    let out = temp.path().join("graph");
    let result = Command::new(cli_bin())
        .args([
            "transpile",
            "--self-contained",
            root.join("main.ds").to_str().unwrap(),
            "--out",
        ])
        .arg(&out)
        .output()
        .expect("transpile graph");
    assert!(
        result.status.success(),
        "{}",
        String::from_utf8_lossy(&result.stderr)
    );
    let main_js = fs::read_to_string(out.join("main.js")).expect("graph main");
    let point_js = fs::read_to_string(out.join("point.js")).expect("graph point");
    assert!(
        main_js.contains("./point.ds"),
        "graph dump must keep .ds specifiers: {main_js}"
    );
    assert!(
        point_js.contains("origin") || point_js.contains("Point"),
        "graph dump must include the imported module: {point_js}"
    );
}

#[test]
fn self_contained_graph_dump_keeps_package_paths() {
    let temp = tempfile::tempdir().expect("tempdir");
    let root = temp.path();
    write(
        &root.join("ds_modules/@deka/io/index.ds"),
        "export fn echo(s: string) {}\n",
    );
    write(
        &root.join("deka.json"),
        r#"{"dependencies":{"@deka/io":"0.0.0"}}"#,
    );
    write(
        &root.join("deka.lock"),
        r#"{
  "lockfileVersion": 1,
  "packages": {
    "@deka/io": ["@deka/io@0.0.0", "local", {}, ""]
  }
}
"#,
    );
    write(
        &root.join("main.ds"),
        "import { echo } from \"io\"\necho(\"hi\")\n",
    );
    let out = root.join("graph");
    let result = Command::new(cli_bin())
        .args([
            "transpile",
            "--self-contained",
            root.join("main.ds").to_str().unwrap(),
            "--out",
        ])
        .arg(&out)
        .output()
        .expect("transpile package graph");
    assert!(
        result.status.success(),
        "{}",
        String::from_utf8_lossy(&result.stderr)
    );
    assert!(
        out.join("ds_modules/@deka/io/index.js").is_file(),
        "package module must keep ds_modules path, dump was: {:?}",
        fs::read_dir(&out)
            .map(|d| d
                .filter_map(|e| e.ok().map(|e| e.path()))
                .collect::<Vec<_>>())
            .unwrap_or_default()
    );
    assert!(
        !out.join("index.js").is_file(),
        "package index.ds must not collapse to graph/index.js"
    );
}
