use std::fs;
use std::process::Command;

fn cli_bin() -> &'static str {
    env!("CARGO_BIN_EXE_dsc")
}

fn write(path: &std::path::Path, source: &str) {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("mkdir");
    }
    fs::write(path, source).expect("write fixture");
}

#[test]
fn file_writes_adjacent_js() {
    let temp = tempfile::tempdir().expect("tempdir");
    let source = temp.path().join("answer.ds");
    write(&source, "export const answer = 42\n");

    let output = Command::new(cli_bin())
        .arg("transpile")
        .arg(&source)
        .output()
        .expect("run transpile");
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );

    let emitted = fs::read_to_string(source.with_extension("js")).expect("emitted JavaScript");
    assert!(
        emitted.starts_with("// Generated by dsc transpile."),
        "{emitted}"
    );
    assert!(emitted.contains("answer"), "{emitted}");
}

#[test]
fn preserve_mirrors_tree_and_rewrites_relative_ds_imports() {
    let temp = tempfile::tempdir().expect("tempdir");
    let root = temp.path().join("src");
    write(&root.join("nested/math.ds"), "export const value = 41\n");
    write(
        &root.join("main.ds"),
        "import { value } from './nested/math.ds'\nexport const answer = value + 1\n",
    );
    let out = temp.path().join("generated");

    let output = Command::new(cli_bin())
        .args(["transpile", root.to_str().unwrap(), "--out"])
        .arg(&out)
        .output()
        .expect("run transpile");
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(out.join("nested/math.js").is_file());
    let main = fs::read_to_string(out.join("main.js")).expect("main");
    assert!(
        main.contains("./nested/math.js"),
        "relative import not rewritten: {main}"
    );
}

#[test]
fn bundle_directory_requires_out_and_inlines_imports() {
    let temp = tempfile::tempdir().expect("tempdir");
    let root = temp.path().join("src");
    write(&root.join("dep.ds"), "export const value = 41\n");
    write(
        &root.join("main.ds"),
        "import { value } from './dep.ds'\nexport const answer = value + 1\n",
    );
    let out = temp.path().join("bundle.js");

    let missing = Command::new(cli_bin())
        .args(["transpile", "--bundle"])
        .arg(&root)
        .output()
        .expect("run transpile");
    assert!(!missing.status.success());
    let stderr = String::from_utf8_lossy(&missing.stderr);
    assert!(stderr.contains("requires --out"), "unexpected: {stderr}");

    let output = Command::new(cli_bin())
        .args(["transpile", "--bundle", "--out"])
        .arg(&out)
        .arg(&root)
        .output()
        .expect("run transpile");
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    let emitted = fs::read_to_string(&out).expect("bundle");
    assert!(
        emitted.starts_with("// Generated by dsc transpile."),
        "{emitted}"
    );
    assert!(emitted.contains("answer"), "{emitted}");
    assert!(
        !emitted.contains("./dep.ds"),
        "bundle still has a relative .ds import: {emitted}"
    );
}

#[test]
fn help_describes_preserve() {
    let output = Command::new(cli_bin())
        .args(["transpile", "--help"])
        .output()
        .expect("run transpile help");
    assert!(output.status.success());
    let text = format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    for expected in ["--preserve", "--bundle", "--treeshake", "--client", "Examples:"] {
        assert!(text.contains(expected), "missing {expected}: {text}");
    }
}

#[test]
fn refuses_to_overwrite_hand_written_js() {
    let temp = tempfile::tempdir().expect("tempdir");
    let source = temp.path().join("answer.ds");
    write(&source, "export const answer = 42\n");
    write(&source.with_extension("js"), "export const mine = 1\n");
    let output = Command::new(cli_bin())
        .arg("transpile")
        .arg(&source)
        .output()
        .expect("run transpile");
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("was not generated by dsc transpile"),
        "unexpected output: {stderr}"
    );
}

#[test]
fn self_contained_inlines_prelude_for_separate_scopes() {
    let temp = tempfile::tempdir().expect("tempdir");
    let root = temp.path().join("src");
    write(
        &root.join("point.ds"),
        "struct Point {\n  x: number;\n}\nexport const origin = Point { x: 0 }\n",
    );
    write(
        &root.join("main.ds"),
        "import { origin } from './point.ds'\nexport const x = origin.x\n",
    );
    let detached = temp.path().join("detached");
    let contained = temp.path().join("contained");

    let a = Command::new(cli_bin())
        .args(["transpile", root.to_str().unwrap(), "--out"])
        .arg(&detached)
        .output()
        .expect("transpile");
    assert!(a.status.success(), "{}", String::from_utf8_lossy(&a.stderr));

    let b = Command::new(cli_bin())
        .args([
            "transpile",
            "--self-contained",
            root.to_str().unwrap(),
            "--out",
        ])
        .arg(&contained)
        .output()
        .expect("transpile self-contained");
    assert!(b.status.success(), "{}", String::from_utf8_lossy(&b.stderr));

    let detached_point = fs::read_to_string(detached.join("point.js")).expect("detached point");
    let contained_point = fs::read_to_string(contained.join("point.js")).expect("contained point");
    let contained_main = fs::read_to_string(contained.join("main.js")).expect("contained main");
    assert!(
        contained_point.contains("__deka_struct") || contained_point.contains("function Point"),
        "self-contained point.js should inline the struct factory: {contained_point}"
    );
    assert!(
        contained_main.contains("./point.ds"),
        "self-contained isolate emit must keep .ds specifiers, got: {contained_main}"
    );
    assert!(
        !contained_main.contains("./point.js"),
        "self-contained isolate emit must not rewrite .ds imports to .js, got: {contained_main}"
    );
    assert!(
        contained_point.len() >= detached_point.len(),
        "self-contained emit should not be smaller than detached"
    );
}

#[test]
fn self_contained_file_out_dir_writes_the_whole_graph() {
    let temp = tempfile::tempdir().expect("tempdir");
    let root = temp.path().join("src");
    write(
        &root.join("point.ds"),
        "struct Point {\n  x: number;\n}\nexport const origin = Point { x: 0 }\n",
    );
    write(
        &root.join("main.ds"),
        "import { origin } from './point.ds'\nexport const x = origin.x\n",
    );
    std::fs::write(root.join("deka.json"), "{}\n").expect("deka.json");
    let out = temp.path().join("graph");
    let result = Command::new(cli_bin())
        .args([
            "transpile",
            "--self-contained",
            root.join("main.ds").to_str().unwrap(),
            "--out",
        ])
        .arg(&out)
        .output()
        .expect("transpile graph");
    assert!(
        result.status.success(),
        "{}",
        String::from_utf8_lossy(&result.stderr)
    );
    let main_js = fs::read_to_string(out.join("main.js")).expect("graph main");
    let point_js = fs::read_to_string(out.join("point.js")).expect("graph point");
    assert!(
        main_js.contains("./point.ds"),
        "graph dump must keep .ds specifiers: {main_js}"
    );
    assert!(
        point_js.contains("origin") || point_js.contains("Point"),
        "graph dump must include the imported module: {point_js}"
    );
}

#[test]
fn self_contained_graph_dump_keeps_package_paths() {
    let temp = tempfile::tempdir().expect("tempdir");
    let root = temp.path();
    write(
        &root.join("ds_modules/@deka/io/index.ds"),
        "export fn echo(s: string) {}\n",
    );
    write(root.join("deka.json"), "{}\n");
    write(
        &root.join("main.ds"),
        "import { echo } from \"io\"\necho(\"hi\")\n",
    );
    let out = root.join("graph");
    let result = Command::new(cli_bin())
        .args([
            "transpile",
            "--self-contained",
            root.join("main.ds").to_str().unwrap(),
            "--out",
        ])
        .arg(&out)
        .output()
        .expect("transpile package graph");
    assert!(
        result.status.success(),
        "{}",
        String::from_utf8_lossy(&result.stderr)
    );
    assert!(
        out.join("ds_modules/@deka/io/index.js").is_file(),
        "package module must keep ds_modules path, dump was: {:?}",
        fs::read_dir(&out)
            .map(|d| d.filter_map(|e| e.ok().map(|e| e.path())).collect::<Vec<_>>())
            .unwrap_or_default()
    );
    assert!(
        !out.join("index.js").is_file(),
        "package index.ds must not collapse to graph/index.js"
    );
}
