use std::fs;
use std::process::Command;

fn cli_bin() -> &'static str {
    env!("CARGO_BIN_EXE_dsc")
}

fn write(path: &std::path::Path, source: &str) {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).expect("mkdir");
    }
    fs::write(path, source).expect("write fixture");
}

#[test]
fn file_writes_adjacent_js() {
    let temp = tempfile::tempdir().expect("tempdir");
    let source = temp.path().join("answer.ds");
    write(&source, "export const answer = 42\n");

    let output = Command::new(cli_bin())
        .arg("transpile")
        .arg(&source)
        .output()
        .expect("run transpile");
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );

    let emitted = fs::read_to_string(source.with_extension("js")).expect("emitted JavaScript");
    assert!(
        emitted.starts_with("// Generated by dsc transpile."),
        "{emitted}"
    );
    assert!(emitted.contains("answer"), "{emitted}");
}

#[test]
fn preserve_mirrors_tree_and_rewrites_relative_ds_imports() {
    let temp = tempfile::tempdir().expect("tempdir");
    let root = temp.path().join("src");
    write(&root.join("nested/math.ds"), "export const value = 41\n");
    write(
        &root.join("main.ds"),
        "import { value } from './nested/math.ds'\nexport const answer = value + 1\n",
    );
    let out = temp.path().join("generated");

    let output = Command::new(cli_bin())
        .args(["transpile", root.to_str().unwrap(), "--out"])
        .arg(&out)
        .output()
        .expect("run transpile");
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert!(out.join("nested/math.js").is_file());
    let main = fs::read_to_string(out.join("main.js")).expect("main");
    assert!(
        main.contains("./nested/math.js"),
        "relative import not rewritten: {main}"
    );
}

#[test]
fn bundle_is_not_pulled() {
    let temp = tempfile::tempdir().expect("tempdir");
    let source = temp.path().join("answer.ds");
    write(&source, "export const answer = 42\n");
    let output = Command::new(cli_bin())
        .args(["transpile", "--bundle"])
        .arg(&source)
        .output()
        .expect("run transpile");
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("not pulled"),
        "unexpected output: {stderr}"
    );
}

#[test]
fn help_describes_preserve() {
    let output = Command::new(cli_bin())
        .args(["transpile", "--help"])
        .output()
        .expect("run transpile help");
    assert!(output.status.success());
    let text = format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    for expected in ["--preserve", "--client", "Examples:"] {
        assert!(text.contains(expected), "missing {expected}: {text}");
    }
}

#[test]
fn refuses_to_overwrite_hand_written_js() {
    let temp = tempfile::tempdir().expect("tempdir");
    let source = temp.path().join("answer.ds");
    write(&source, "export const answer = 42\n");
    write(&source.with_extension("js"), "export const mine = 1\n");
    let output = Command::new(cli_bin())
        .arg("transpile")
        .arg(&source)
        .output()
        .expect("run transpile");
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("was not generated by dsc transpile"),
        "unexpected output: {stderr}"
    );
}
