use deka_native_ir::{Number, Program, Template, Text};

/// Emit executable Rust from the checked native program, not an embedded interpreter.
pub fn emit_rust(program: &Program) -> String {
    let initial: Vec<_> = program
        .states
        .iter()
        .map(|s| format!("{:?}", s.initial))
        .collect();
    let handlers: Vec<_> = program
        .handlers
        .iter()
        .enumerate()
        .map(|(i, h)| format!("{i} => {{ state[{}] = {}; }},", h.state, number(&h.value)))
        .collect();
    format!(
        r#"// Generated by dsc-native. Application logic is native Rust.
use deka_native_ui::{{Application, Node, Style}};
struct NativeApp;
impl Application for NativeApp {{
    fn initial_state(&self) -> Vec<f64> {{ vec![{}] }}
    fn render(&self, state: &[f64]) -> Node {{ let _ = state; {} }}
    fn event(&self, handler: usize, state: &mut [f64]) {{ let _ = &state; match handler {{ {} _ => {{}} }} }}
}}
fn main() {{ deka_native_ui::run(NativeApp); }}
"#,
        initial.join(","),
        node(&program.root),
        handlers.join("\n")
    )
}
fn number(expr: &Number) -> String {
    match expr {
        Number::Literal(n) => format!("{n:?}"),
        Number::State(i) => format!("state[{i}]"),
        Number::Add(a, b) => format!("({} + {})", number(a), number(b)),
        Number::Sub(a, b) => format!("({} - {})", number(a), number(b)),
        Number::Mul(a, b) => format!("({} * {})", number(a), number(b)),
    }
}
fn node(template: &Template) -> String {
    let text = match &template.text {
        None => "None".into(),
        Some(Text::Literal(t)) => format!("Some({t:?}.to_owned())"),
        Some(Text::Number(n)) => format!("Some(({}).to_string())", number(n)),
    };
    let s = &template.style;
    format!(
        "Node {{ id: {:?}.into(), style: Style {{ row: {}, padding: {:?}, gap: {:?}, background: {:?}, color: {:?}, font_size: {:?}, radius: {:?}, width: {:?}, height: {:?} }}, text: {}, on_click: {:?}, children: vec![{}] }}",
        template.id,
        s.row,
        s.padding,
        s.gap,
        s.background,
        s.color,
        s.font_size,
        s.radius,
        s.width,
        s.height,
        text,
        template.on_click,
        template
            .children
            .iter()
            .map(node)
            .collect::<Vec<_>>()
            .join(",")
    )
}
