use deka_native_ir::{Condition, Number, Program, Template, Text};

/// Emit executable Rust from the checked native program, not an embedded interpreter.
pub fn emit_rust(program: &Program) -> String {
    let initial: Vec<_> = program
        .states
        .iter()
        .map(|s| format!("{:?}", s.initial))
        .collect();
    let handlers: Vec<_> = program
        .handlers
        .iter()
        .enumerate()
        .map(|(i, h)| format!("{i} => {{ state[{}] = {}; }},", h.state, number(&h.value)))
        .collect();
    format!(
        r#"// Generated by dsc-native. Application logic is native Rust.
use deka_native_ui::{{Application, Node, Style, Length, Edges, Align, Justify, Motion, Keyframe}};
struct NativeApp;
impl Application for NativeApp {{
    fn initial_state(&self) -> Vec<f64> {{ vec![{}] }}
    fn render(&self, state: &[f64]) -> Node {{ let _ = state; {} }}
    fn event(&self, handler: usize, state: &mut [f64]) {{ let _ = &state; match handler {{ {} _ => {{}} }} }}
}}
fn main() {{ deka_native_ui::run(NativeApp); }}
"#,
        initial.join(","),
        node(&program.root),
        handlers.join("\n")
    )
}
fn number(expr: &Number) -> String {
    fn emit(expr: &Number, parent: u8, right: bool) -> String {
        let (text, precedence) = match expr {
            Number::Literal(n) => (format!("{n:?}"), 3),
            Number::State(i) => (format!("state[{i}]"), 3),
            Number::Add(a, b) => (format!("{} + {}", emit(a, 1, false), emit(b, 1, true)), 1),
            Number::Sub(a, b) => (format!("{} - {}", emit(a, 1, false), emit(b, 1, true)), 1),
            Number::Mul(a, b) => (format!("{} * {}", emit(a, 2, false), emit(b, 2, true)), 2),
        };
        if precedence < parent || (right && precedence == parent) {
            format!("({text})")
        } else {
            text
        }
    }
    emit(expr, 0, false)
}

fn node(template: &Template) -> String {
    let text = match &template.text {
        None => "None".into(),
        Some(Text::Literal(t)) => format!("Some({t:?}.to_owned())"),
        Some(Text::Number(n)) => format!("Some(({}).to_string())", number(n)),
    };
    format!(
        "Node {{ id: {:?}.into(), style: {}, text: {}, on_click: {:?}, children: {{ let mut children = Vec::new(); {} children }} }}",
        template.id,
        template.style_when.as_ref().map_or_else(
            || style(&template.style),
            |s| format!(
                "if {} {{ {} }} else {{ {} }}",
                match &s.condition {
                    Condition::Equal(a, b) => format!("({}) == ({})", number(a), number(b)),
                },
                style(&s.then_style),
                style(&s.else_style)
            )
        ),
        text,
        template.on_click,
        template
            .children
            .iter()
            .map(|child| {
                let push = format!("children.push({});", node(child));
                match &child.visible_when {
                    Some(Condition::Equal(a, b)) => {
                        format!("if ({}) == ({}) {{ {push} }}", number(a), number(b))
                    }
                    None => push,
                }
            })
            .collect::<Vec<_>>()
            .join("\n")
    )
}
fn style(s: &deka_native_ir::Style) -> String {
    let align_self = s
        .align_self
        .map_or("None".to_owned(), |a| format!("Some(Align::{a:?})"));
    format!(
        "Style {{ row: {:?}, wrap: {:?}, grow: {:?}, shrink: {:?}, align: Align::{:?}, align_self: {}, justify: Justify::{:?}, padding: {:?}, margin: {:?}, gap_x: {:?}, gap_y: {:?}, background: {:?}, color: {:?}, font_size: {:?}, radius: {:?}, width: Length::{:?}, height: Length::{:?}, min_width: Length::{:?}, min_height: Length::{:?}, max_width: Length::{:?}, max_height: Length::{:?}, clip: {:?}, nowrap: {:?}, opacity: {:?}, translate_x: {:?}, translate_y: {:?}, transition: {:?}, duration_ms: {:?}, easing: {:?}, scale: {:?}, rotate: {:?}, motion: {} }}",
        s.row,
        s.wrap,
        s.grow,
        s.shrink,
        s.align,
        align_self,
        s.justify,
        s.padding,
        s.margin,
        s.gap_x,
        s.gap_y,
        s.background,
        s.color,
        s.font_size,
        s.radius,
        s.width,
        s.height,
        s.min_width,
        s.min_height,
        s.max_width,
        s.max_height,
        s.clip,
        s.nowrap,
        s.opacity,
        s.translate_x,
        s.translate_y,
        s.transition,
        s.duration_ms,
        s.easing,
        s.scale,
        s.rotate,
        format_args!(
            "Motion {{ stiffness: {:?}, damping: {:?}, delay_ms: {:?}, stagger_ms: {:?}, enter: {}, exit: {}, layout: {}, frames: vec!{:?}, repeats: {}, alternate: {} }}",
            s.motion.stiffness,
            s.motion.damping,
            s.motion.delay_ms,
            s.motion.stagger_ms,
            s.motion.enter,
            s.motion.exit,
            s.motion.layout,
            s.motion.frames,
            s.motion.repeats,
            s.motion.alternate
        )
    )
}
