// Generated by dsc transpile. Do not edit manually.
"use strict";

import { handle, read } from "./foreign.mjs";
export { handle };
if ((($__deka_foreign) => { if ($__deka_foreign == null) { const e = new Error("summoned function returned null or undefined"); e.name = "BoundaryError"; e[Symbol.for("deka.BoundaryError")] = true; throw e; } return $__deka_foreign; })(read((($__deka_foreign) => { if ($__deka_foreign == null) { const e = new Error("summoned function returned null or undefined"); e.name = "BoundaryError"; e[Symbol.for("deka.BoundaryError")] = true; throw e; } return $__deka_foreign; })(handle()))) != 42) {
(() => { throw new Error(String("handle identity")); })();
}