use core::{CommandSpec, Context, ParamSpec, Registry};
use std::fs;
use std::path::{Path, PathBuf};

use crate::compile_helper::{
    compile_source_js, is_deka_source_path, rewrite_relative_ds_imports,
};

const GENERATED_MARKER: &str = "// Generated by dsc transpile. Do not edit manually.\n";

const COMMAND: CommandSpec = CommandSpec {
    name: "transpile",
    category: "compiler",
    summary: "emit JavaScript from a .ds file or directory",
    aliases: &["emit"],
    subcommands: &[],
    handler: cmd,
};

pub fn register(registry: &mut Registry) {
    registry.add_command(COMMAND);
    registry.add_flag(core::FlagSpec {
        name: "--preserve",
        aliases: &[],
        description: "preserve a directory's module tree (default for directories)",
    });
    registry.add_flag(core::FlagSpec {
        name: "--bundle",
        aliases: &[],
        description: "emit one resolved JavaScript module graph",
    });
    registry.add_flag(core::FlagSpec {
        name: "--treeshake",
        aliases: &[],
        description: "apply JavaScript optimization to emitted modules",
    });
    registry.add_flag(core::FlagSpec {
        name: "--client",
        aliases: &[],
        description: "treat the entry as a client bundle (ui/server is a build failure)",
    });
    registry.add_param(ParamSpec {
        name: "--out",
        description: "output .js file (file) or output directory (preserve)",
    });
}

fn cmd(context: &Context) {
    if context.args.flags.get("--help").copied().unwrap_or(false)
        || context.args.flags.get("-H").copied().unwrap_or(false)
        || context.args.flags.get("help").copied().unwrap_or(false)
    {
        stdio::raw(usage());
        return;
    }
    if let Err(err) = run(context) {
        stdio::error("transpile", &err);
        std::process::exit(1);
    }
}

fn run(context: &Context) -> Result<(), String> {
    let input = context
        .args
        .positionals
        .first()
        .ok_or_else(|| usage().to_string())?;
    if context.args.positionals.len() != 1 {
        return Err(usage().to_string());
    }
    if context.args.flags.get("--bundle").copied().unwrap_or(false) {
        return Err(
            "`dsc transpile --bundle` needs the compiler bundler; not pulled yet (it currently lives next to runtime_core). Use --preserve for per-module emit.".to_string(),
        );
    }
    if context
        .args
        .flags
        .get("--treeshake")
        .copied()
        .unwrap_or(false)
    {
        return Err(
            "`dsc transpile --treeshake` needs the compiler optimizer; not pulled yet.".to_string(),
        );
    }

    let input = PathBuf::from(input);
    let input = if input.is_absolute() {
        input
    } else {
        context.env.cwd.join(input)
    };
    let output = context.args.params.get("--out").map(PathBuf::from);
    let client = context
        .args
        .flags
        .get("--client")
        .copied()
        .unwrap_or(false);

    match (input.is_file(), input.is_dir()) {
        (true, _) => transpile_file(&input, output.as_deref(), client, &context.env.cwd),
        (_, true) => transpile_directory(&input, output.as_deref(), client, &context.env.cwd),
        _ => Err(format!("input path does not exist: {}", input.display())),
    }
}

fn usage() -> &'static str {
    "usage: dsc transpile <file-or-directory> [--preserve] [--client] [--out <path>]\n\nModes:\n  file: writes adjacent <name>.js by default; --out selects the output file\n  directory: --preserve is the default and mirrors .ds paths as .js paths\n  --client: fail the build if the graph can reach ui/server\n\n--bundle and --treeshake are reserved; they are not in this repo yet.\n\nExamples:\n  dsc transpile app/main.ds\n  dsc transpile app --preserve --out generated\n  dsc transpile island.dsx --client --out dist/island.js"
}

fn transpile_file(
    input: &Path,
    out: Option<&Path>,
    client: bool,
    cwd: &Path,
) -> Result<(), String> {
    require_ds(input)?;
    let output = out
        .map(PathBuf::from)
        .unwrap_or_else(|| input.with_extension("js"));
    if output == input {
        return Err("output path must differ from the .ds input path".to_string());
    }
    let js = build_module(input, cwd, client)?;
    write_generated_js(&output, &js)?;
    stdio::success(&format!(
        "transpiled {} -> {}",
        input.display(),
        output.display()
    ));
    Ok(())
}

fn transpile_directory(
    input: &Path,
    out: Option<&Path>,
    client: bool,
    cwd: &Path,
) -> Result<(), String> {
    let sources = collect_ds_sources(input)?;
    if sources.is_empty() {
        return Err(format!("no .ds files found under {}", input.display()));
    }
    let output_root = out
        .map(PathBuf::from)
        .unwrap_or_else(|| input.to_path_buf());
    if output_root.extension().is_some() {
        return Err("directory --preserve --out must name a directory".to_string());
    }
    for source in &sources {
        let rel = source
            .strip_prefix(input)
            .map_err(|_| "failed to preserve source tree".to_string())?;
        let output = output_root.join(rel).with_extension("js");
        let js = build_module(source, cwd, client)?;
        write_generated_js(&output, &js)?;
    }
    stdio::success(&format!(
        "transpiled {} -> {}",
        input.display(),
        output_root.display()
    ));
    Ok(())
}

fn build_module(input: &Path, cwd: &Path, client: bool) -> Result<String, String> {
    let js = compile_source_js(input, cwd, client)?;
    Ok(format!(
        "{GENERATED_MARKER}{}",
        rewrite_relative_ds_imports(js)
    ))
}

fn write_generated_js(path: &Path, js: &str) -> Result<(), String> {
    if path.exists() {
        let existing = fs::read_to_string(path)
            .map_err(|err| format!("failed to read {}: {err}", path.display()))?;
        if !existing.starts_with(GENERATED_MARKER) {
            return Err(format!(
                "output collision: {} already exists and was not generated by dsc transpile",
                path.display()
            ));
        }
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|err| format!("failed to create {}: {err}", parent.display()))?;
    }
    let tmp = path.with_extension("js.tmp-dsc");
    fs::write(&tmp, js).map_err(|err| format!("failed to write {}: {err}", tmp.display()))?;
    fs::rename(&tmp, path)
        .map_err(|err| format!("failed to write {}: {err}", path.display()))?;
    Ok(())
}

fn collect_ds_sources(root: &Path) -> Result<Vec<PathBuf>, String> {
    let mut out = Vec::new();
    collect_ds_sources_inner(root, &mut out)?;
    out.sort();
    Ok(out)
}

fn collect_ds_sources_inner(dir: &Path, out: &mut Vec<PathBuf>) -> Result<(), String> {
    let mut entries = fs::read_dir(dir)
        .map_err(|err| format!("failed to read {}: {err}", dir.display()))?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|err| format!("failed to read {}: {err}", dir.display()))?;
    entries.sort_by_key(|entry| entry.file_name());
    for entry in entries {
        let path = entry.path();
        let name = entry.file_name();
        let name = name.to_string_lossy();
        if path.is_dir() {
            if matches!(
                name.as_ref(),
                "ds_modules" | "php_modules" | ".deka" | "node_modules" | "target" | ".git"
            ) {
                continue;
            }
            collect_ds_sources_inner(&path, out)?;
        } else if is_deka_source_path(&path) {
            out.push(path);
        }
    }
    Ok(())
}

fn require_ds(path: &Path) -> Result<(), String> {
    if is_deka_source_path(path) {
        Ok(())
    } else {
        Err(format!(
            "DekaScript uses .ds or .dsx; cannot transpile {}",
            path.display()
        ))
    }
}
