use bundler::{bundle_virtual_entry, optimize_emitted_module, BuildOptions, VirtualSource};
use core::{CommandSpec, Context, ParamSpec, Registry};
use deka_compile::format_diagnostics;
use deka_compile::module_graph::{self, GraphCompileOptions};
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use crate::compile_helper::{
    compile_graph_modules, compile_source_js, find_project_root, is_deka_source_path,
    rewrite_relative_ds_imports,
};

const GENERATED_MARKER: &str = "// Generated by dsc transpile. Do not edit manually.\n";

const COMMAND: CommandSpec = CommandSpec {
    name: "transpile",
    category: "compiler",
    summary: "emit JavaScript from a .ds file or directory",
    aliases: &["emit"],
    subcommands: &[],
    handler: cmd,
};

pub fn register(registry: &mut Registry) {
    registry.add_command(COMMAND);
    registry.add_flag(core::FlagSpec {
        name: "--preserve",
        aliases: &[],
        description: "preserve a directory's module tree (default for directories)",
    });
    registry.add_flag(core::FlagSpec {
        name: "--bundle",
        aliases: &[],
        description: "emit one resolved JavaScript module graph",
    });
    registry.add_flag(core::FlagSpec {
        name: "--treeshake",
        aliases: &[],
        description: "apply JavaScript optimization to emitted modules",
    });
    registry.add_flag(core::FlagSpec {
        name: "--client",
        aliases: &[],
        description: "treat the entry as a client bundle (ui/server is a build failure)",
    });
    registry.add_flag(core::FlagSpec {
        name: "--self-contained",
        aliases: &[],
        description: "inline each module's prelude so files can load in separate scopes",
    });
    registry.add_param(ParamSpec {
        name: "--out",
        description: "output .js file (file) or output directory (preserve)",
    });
}

fn cmd(context: &Context) {
    if context.args.flags.get("--help").copied().unwrap_or(false)
        || context.args.flags.get("-H").copied().unwrap_or(false)
        || context.args.flags.get("help").copied().unwrap_or(false)
    {
        stdio::raw(usage());
        return;
    }
    if let Err(err) = run(context) {
        stdio::error("transpile", &err);
        std::process::exit(1);
    }
}

fn run(context: &Context) -> Result<(), String> {
    let input = context
        .args
        .positionals
        .first()
        .ok_or_else(|| usage().to_string())?;
    if context.args.positionals.len() != 1 {
        return Err(usage().to_string());
    }

    let input = PathBuf::from(input);
    let input = if input.is_absolute() {
        input
    } else {
        context.env.cwd.join(input)
    };
    let mode = TranspileMode::from_context(context, &input)?;
    let output = context.args.params.get("--out").map(PathBuf::from);
    let treeshake = context
        .args
        .flags
        .get("--treeshake")
        .copied()
        .unwrap_or(false);
    let client = context.args.flags.get("--client").copied().unwrap_or(false);
    let self_contained = context
        .args
        .flags
        .get("--self-contained")
        .copied()
        .unwrap_or(false);

    match (input.is_file(), input.is_dir()) {
        (true, _) => transpile_file(
            &input,
            output.as_deref(),
            mode,
            treeshake,
            client,
            self_contained,
            &context.env.cwd,
        ),
        (_, true) => transpile_directory(
            &input,
            output.as_deref(),
            mode,
            treeshake,
            client,
            self_contained,
            &context.env.cwd,
        ),
        _ => Err(format!("input path does not exist: {}", input.display())),
    }
}

fn usage() -> &'static str {
    "usage: dsc transpile <file-or-directory> [--preserve|--bundle] [--treeshake] [--client] [--out <path>]\n\nModes:\n  file: writes adjacent <name>.js by default; --out selects the output file\n  directory: --preserve is the default and mirrors .ds paths as .js paths\n  directory --bundle: requires --out <file.js> and emits one resolved graph\n  --treeshake: minify emitted JavaScript in either mode\n  --client: fail the build if the graph can reach ui/server\n  --self-contained: inline per-module prelude (isolate ESM loader)\n\nExamples:\n  dsc transpile app/main.ds\n  dsc transpile app --preserve --out generated\n  dsc transpile app --bundle --out dist/app.js --treeshake\n  dsc transpile island.dsx --bundle --client --out dist/island.js"
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum TranspileMode {
    Preserve,
    Bundle,
}

impl TranspileMode {
    fn from_context(context: &Context, input: &Path) -> Result<Self, String> {
        let preserve = context
            .args
            .flags
            .get("--preserve")
            .copied()
            .unwrap_or(false);
        let bundle = context.args.flags.get("--bundle").copied().unwrap_or(false);
        if preserve && bundle {
            return Err("--preserve and --bundle cannot be used together".to_string());
        }
        if bundle {
            Ok(Self::Bundle)
        } else if input.is_dir() || preserve {
            Ok(Self::Preserve)
        } else {
            Ok(Self::Preserve)
        }
    }
}

fn out_is_graph_dir(out: &Path) -> bool {
    out.is_dir() || out.extension().is_none()
}

fn transpile_file(
    input: &Path,
    out: Option<&Path>,
    mode: TranspileMode,
    treeshake: bool,
    client: bool,
    self_contained: bool,
    cwd: &Path,
) -> Result<(), String> {
    require_ds(input)?;
    // Isolate hosts pass `--self-contained --out <dir>` so every reachable
    // module (including ds_modules packages) lands in the map, not just the
    // entry. A `.js` --out still means "write the entry file only".
    if self_contained && mode != TranspileMode::Bundle {
        if let Some(output) = out {
            if out_is_graph_dir(output) {
                return write_self_contained_graph(input, output, cwd, treeshake, client);
            }
        }
    }
    let output = out
        .map(PathBuf::from)
        .unwrap_or_else(|| input.with_extension("js"));
    if output == input {
        return Err("output path must differ from the .ds input path".to_string());
    }
    let js = if mode == TranspileMode::Bundle {
        build_bundle(input, cwd, treeshake, client)?
    } else {
        build_module(input, cwd, treeshake, client, self_contained)?
    };
    write_generated_js(&output, &js)?;
    stdio::success(&format!(
        "transpiled {} -> {}",
        input.display(),
        output.display()
    ));
    Ok(())
}

fn write_self_contained_graph(
    input: &Path,
    out: &Path,
    cwd: &Path,
    treeshake: bool,
    client: bool,
) -> Result<(), String> {
    let (entry, modules) = compile_graph_modules(input, cwd, client, true)?;
    let project_root = find_project_root(cwd, input)
        .or_else(|| input.parent().map(Path::to_path_buf))
        .unwrap_or_else(|| PathBuf::from("."));
    let project_root = fs::canonicalize(&project_root).unwrap_or(project_root);
    if modules.is_empty() {
        return Err("module graph did not emit any modules".to_string());
    }
    for (source, mut js) in modules {
        if treeshake {
            js = optimize_emitted_module(&js, &source.with_extension("js"))?;
        }
        let source = fs::canonicalize(&source).unwrap_or(source);
        let rel = source
            .strip_prefix(&project_root)
            .unwrap_or_else(|_| Path::new(source.file_name().unwrap_or(source.as_os_str())));
        let dest = out.join(rel).with_extension("js");
        write_generated_js(&dest, &format!("{GENERATED_MARKER}{js}"))?;
    }
    let _ = entry;
    stdio::success(&format!(
        "transpiled {} -> {}",
        input.display(),
        out.display()
    ));
    Ok(())
}

fn transpile_directory(
    input: &Path,
    out: Option<&Path>,
    mode: TranspileMode,
    treeshake: bool,
    client: bool,
    self_contained: bool,
    cwd: &Path,
) -> Result<(), String> {
    let sources = collect_ds_sources(input)?;
    if sources.is_empty() {
        return Err(format!("no .ds files found under {}", input.display()));
    }
    match mode {
        TranspileMode::Bundle => {
            let output = out.ok_or_else(|| {
                "directory --bundle requires --out <file.js> so the bundle target is unambiguous"
                    .to_string()
            })?;
            if output.is_dir() || output.extension().and_then(|ext| ext.to_str()) != Some("js") {
                return Err("directory --bundle --out must name a .js file".to_string());
            }
            let entry = directory_entry(input, &sources)?;
            let js = build_bundle(&entry, cwd, treeshake, client)?;
            write_generated_js(output, &js)?;
            stdio::success(&format!(
                "transpiled {} -> {}",
                input.display(),
                output.display()
            ));
        }
        TranspileMode::Preserve => {
            let output_root = out
                .map(PathBuf::from)
                .unwrap_or_else(|| input.to_path_buf());
            if output_root.extension().is_some() {
                return Err("directory --preserve --out must name a directory".to_string());
            }
            for source in &sources {
                let rel = source
                    .strip_prefix(input)
                    .map_err(|_| "failed to preserve source tree".to_string())?;
                let output = output_root.join(rel).with_extension("js");
                let js = build_module(source, cwd, treeshake, client, self_contained)?;
                write_generated_js(&output, &js)?;
            }
            stdio::success(&format!(
                "transpiled {} -> {}",
                input.display(),
                output_root.display()
            ));
        }
    }
    Ok(())
}

fn directory_entry(root: &Path, sources: &[PathBuf]) -> Result<PathBuf, String> {
    for name in ["main.ds", "index.ds", "app.ds"] {
        let candidate = root.join(name);
        if candidate.is_file() {
            return Ok(candidate);
        }
    }
    if sources.len() == 1 {
        return Ok(sources[0].clone());
    }
    Err(format!(
        "directory --bundle needs an entry file (main.ds, index.ds, or app.ds) under {}",
        root.display()
    ))
}

fn build_module(
    input: &Path,
    cwd: &Path,
    treeshake: bool,
    client: bool,
    self_contained: bool,
) -> Result<String, String> {
    let mut js = compile_source_js(input, cwd, client, self_contained)?;
    // On-disk preserve mode rewrites relative `.ds` imports to `.js` peers.
    // `--self-contained` is for the isolate ESM loader, which resolves `.ds`
    // specifiers from memory — rewriting those to `.js` makes Deno ENOENT.
    if !self_contained {
        js = rewrite_relative_ds_imports(js);
    }
    if treeshake {
        js = optimize_emitted_module(&js, &input.with_extension("js"))?;
    }
    Ok(format!("{GENERATED_MARKER}{js}"))
}

fn build_bundle(input: &Path, cwd: &Path, treeshake: bool, client: bool) -> Result<String, String> {
    let entry = fs::canonicalize(input)
        .map_err(|err| format!("failed to resolve {}: {err}", input.display()))?;
    let project_root = find_project_root(cwd, &entry)
        .or_else(|| entry.parent().map(Path::to_path_buf))
        .unwrap_or_else(|| PathBuf::from("."));
    let loader = module_graph::FsModuleLoader::new(project_root.clone());
    let graph = module_graph::compile_module_graph_with_options(
        &entry,
        &loader,
        GraphCompileOptions {
            client,
            ..Default::default()
        },
    )
    .map_err(|diagnostics| format_diagnostics(&diagnostics))?;
    let provider = Arc::new(GraphSourceProvider {
        modules: graph.modules,
    });
    let js = bundle_virtual_entry(
        &entry,
        BuildOptions {
            project_root,
            minify: treeshake,
            iife: false,
            client,
        },
        provider,
    )?;
    Ok(format!("{GENERATED_MARKER}{js}"))
}

struct GraphSourceProvider {
    modules: HashMap<PathBuf, String>,
}

impl VirtualSource for GraphSourceProvider {
    fn load_virtual(&self, path: &Path) -> Result<Option<String>, String> {
        let canon = fs::canonicalize(path).unwrap_or_else(|_| path.to_path_buf());
        if let Some(js) = self.modules.get(&canon).or_else(|| self.modules.get(path)) {
            return Ok(Some(js.clone()));
        }
        Ok(None)
    }
}

fn write_generated_js(path: &Path, js: &str) -> Result<(), String> {
    if path.exists() {
        let existing = fs::read_to_string(path)
            .map_err(|err| format!("failed to read {}: {err}", path.display()))?;
        if !existing.starts_with(GENERATED_MARKER) {
            return Err(format!(
                "output collision: {} already exists and was not generated by dsc transpile",
                path.display()
            ));
        }
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|err| format!("failed to create {}: {err}", parent.display()))?;
    }
    let tmp = path.with_extension("js.tmp-dsc");
    fs::write(&tmp, js).map_err(|err| format!("failed to write {}: {err}", tmp.display()))?;
    fs::rename(&tmp, path).map_err(|err| format!("failed to write {}: {err}", path.display()))?;
    Ok(())
}

fn collect_ds_sources(root: &Path) -> Result<Vec<PathBuf>, String> {
    let mut out = Vec::new();
    collect_ds_sources_inner(root, &mut out)?;
    out.sort();
    Ok(out)
}

fn collect_ds_sources_inner(dir: &Path, out: &mut Vec<PathBuf>) -> Result<(), String> {
    let mut entries = fs::read_dir(dir)
        .map_err(|err| format!("failed to read {}: {err}", dir.display()))?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|err| format!("failed to read {}: {err}", dir.display()))?;
    entries.sort_by_key(|entry| entry.file_name());
    for entry in entries {
        let path = entry.path();
        let name = entry.file_name();
        let name = name.to_string_lossy();
        if path.is_dir() {
            if matches!(
                name.as_ref(),
                "ds_modules" | "php_modules" | ".deka" | "node_modules" | "target" | ".git"
            ) {
                continue;
            }
            collect_ds_sources_inner(&path, out)?;
        } else if is_deka_source_path(&path) {
            out.push(path);
        }
    }
    Ok(())
}

fn require_ds(path: &Path) -> Result<(), String> {
    if is_deka_source_path(path) {
        Ok(())
    } else {
        Err(format!(
            "DekaScript uses .ds or .dsx; cannot transpile {}",
            path.display()
        ))
    }
}
