//! Parser helpers: operator precedence, token names, and EOF sentinel.

use crate::ast::{BinOp, Span};
use crate::lexer::{Token, TokenKind};

pub(super) fn infix_info(kind: TokenKind) -> Option<(u8, u8, BinOp)> {
    use TokenKind::*;
    Some(match kind {
        // Assignment and compound assignment are right-associative and bind
        // looser than every other operator.
        Eq => (0, 0, BinOp::Assign),
        PlusEq => (0, 0, BinOp::AddAssign),
        MinusEq => (0, 0, BinOp::SubAssign),
        StarEq => (0, 0, BinOp::MulAssign),
        SlashEq => (0, 0, BinOp::DivAssign),
        PercentEq => (0, 0, BinOp::ModAssign),
        Or => (1, 2, BinOp::Or),
        And => (3, 4, BinOp::And),
        Pipe => (3, 4, BinOp::Pipe),
        EqEq => (5, 6, BinOp::Eq),
        TripleEq => (5, 6, BinOp::Eq),
        NotEq => (5, 6, BinOp::Ne),
        Lt => (7, 8, BinOp::Lt),
        Le => (7, 8, BinOp::Le),
        Gt => (7, 8, BinOp::Gt),
        Ge => (7, 8, BinOp::Ge),
        Plus => (9, 10, BinOp::Add),
        Minus => (9, 10, BinOp::Sub),
        Star => (11, 12, BinOp::Mul),
        Slash => (11, 12, BinOp::Div),
        Percent => (11, 12, BinOp::Mod),
        _ => return std::option::Option::None,
    })
}

pub(super) fn eof_token<'a>() -> Token<'a> {
    Token {
        kind: TokenKind::Eof,
        text: "",
        span: Span::dummy(),
    }
}

pub(super) fn token_name(kind: TokenKind) -> &'static str {
    use TokenKind::*;
    match kind {
        Bar => "`|`",
        Number => "number",
        BigInt => "bigint",
        String => "string",
        BacktickString => "backtick string",
        RawJs => "raw JavaScript",
        True => "`true`",
        False => "`false`",
        None => "`none`",
        Identifier => "identifier",
        Const => "`const`",
        Let => "`let`",
        Mut => "`mut`",
        Function => "`function`",
        Fn => "`fn`",
        Struct => "`struct`",
        Enum => "`enum`",
        Interface => "`interface`",
        Type => "`type`",
        Alias => "`alias`",
        Import => "`import`",
        Export => "`export`",
        From => "`from`",
        As => "`as`",
        If => "`if`",
        Else => "`else`",
        For => "`for`",
        Of => "`of`",
        Return => "`return`",
        Match => "`match`",
        Unsafe => "`unsafe`",
        Bridge => "`bridge`",
        Await => "`await`",
        Async => "`async`",
        Super => "`super`",
        Pub => "`pub`",
        Break => "`break`",
        Continue => "`continue`",
        Plus => "`+`",
        Minus => "`-`",
        Star => "`*`",
        Slash => "`/`",
        Percent => "`%`",
        PlusEq => "`+=`",
        MinusEq => "`-=`",
        StarEq => "`*=`",
        SlashEq => "`/=`",
        PercentEq => "`%=`",
        Eq => "`=`",
        EqEq => "`==`",
        TripleEq => "`===`",
        NotEq => "`!=`",
        Lt => "`<`",
        Le => "`<=`",
        Gt => "`>`",
        Ge => "`>=`",
        And => "`&&`",
        Or => "`||`",
        Not => "`!`",
        Ampersand => "`&`",
        Pipe => "`|`",
        Caret => "`^`",
        Shl => "`<<`",
        Shr => "`>>`",
        LParen => "`(`",
        RParen => "`)`",
        LBrace => "`{`",
        RBrace => "`}`",
        LBracket => "`[`",
        RBracket => "`]`",
        Comma => "`,`",
        Semicolon => "`;`",
        Colon => "`:`",
        DoubleColon => "`::`",
        Dot => "`.`",
        Arrow => "`->`",
        FatArrow => "`=>`",
        Question => "`?`",
        Spread => "`...`",
        LtJsx => "`<`",
        GtJsx => "`>`",
        SlashJsx => "`/`",
        Newline => "newline",
        Comment => "comment",
        Eof => "end of file",
        Error => "error",
    }
}
